spring:
  application:
    name: hong
  data:
    mongodb:
      uri: mongodb://root:hong@127.0.0.1:19017/hong
  redis:
    url: redis://hong@127.0.0.1:19379/0
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

server:
  port: 19001

sa-token:
  token-name: ht
  # 不使用cookie
  is-read-cookie: false
  is-read-body: false