version: '3.1'

services:

  redis:
    image: redis:6.2
    ports:
      - 19379:6379
    restart: always
    command: redis-server --requirepass hong
    volumes:
      - ./db-env/redisdata:/data

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 19017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hong
    volumes:
      - ./db-env/mongodata:/data/db

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 19018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hong
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    volumes: 
      - ./db-env/rabbitmqdata:/var/lib/rabbitmq
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf