# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    environment: registry

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - run: |
        java -version
        mvn -version

    - name: Build with Maven
      run: mvn -B package --file src/pom.xml

    - name: Docker push test
      if: ${{ contains(github.ref, 'refs/heads/develop') }}
      run: |
        docker build -t ${{ secrets.API_IMAGE }}:dev${{ github.run_number }} .
        docker push ${{ secrets.API_IMAGE }}:dev${{ github.run_number }}
